language: node_js

services:
  - postgresql

node_js:
  - 4.4

env:
  - DB=postgres

postgres:
  adapter: postgresql
  database: wwc_chatroom_development
  username: postgres

before_script:
  - psql -c 'create database wwc_chatroom_development;' -U postgres
  - "npm install"
  - "./node_modules/.bin/sequelize db:migrate"

script:
  - "npm test"
