language: node_js

sudo: required

services:
  - postgresql

node_js:
  - 4.4

env:
  - CXX=g++-4.8
  - NODE_ENV=staging
  - DB=postgresql

postgres:
  adapter: postgresql
  database: wwc_chatroom_development
  username: postgres

before_script:
  - "npm install"
  - psql -c 'create database wwc_chatroom_development;' -U postgres

script:
  - "./node_modules/.bin/sequelize db:migrate --env Staging"
  - "npm test"
