language: node_js

sudo: required

services:
  - postgresql

node_js:
  - 4.4

env:
  - NODE_ENV=staging
  - DB=postgres

postgres:
  adapter: postgresql
  database: wwc_chatroom_development
  username: postgres

before_script:
  - psql -c 'wwc_chatroom_development;' -U postgres
  - "npm install"
  - "./node_modules/.bin/sequelize db:migrate --env Staging"

script:
  - "npm test"
