language: node_js

sudo: required

services:
  - postgresql

node_js:
  - 4.4

env:
  - CXX=g++-4.8
  - NODE_ENV=staging
  - DB=postgresql

before_script:
  - psql -c 'create database wwc_chatroom_development;' -U postgres
  - "npm install"
  - "./node_modules/.bin/sequelize db:migrate"

script:
  - "npm test"
